---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=roles/' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook roles/core.role/tests/test.yml -i  roles/core.role/tests/inventory --syntax-check
