# Copyright 2017 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).
---
# handlers file for core

- name: restart-fail2ban
  service: name=fail2ban state=restarted enabled=true
  
- name: restart-sshd
  service: name=ssh state=restarted enabled=true
