# Copyright 2016 LasLabs Inc.
# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).
---
galaxy_info:
  author: Ted Salmon
  description: Role allows you to provision a new Fedora 19+ Server
  company: LasLabs, Inc.
  license: Apache 2.0
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
  galaxy_tags:
  - system
  - setup
dependencies: []
